---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: public
    volumes:
      - ./secrets/wg0.conf:/gluetun/wireguard/wg0.conf
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
    ports:
      - 8023:8023/tcp
      - 8031:8031/tcp
      - 5432:5432/tcp
      - 8123:8123/tcp
