---
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      # this is necesssary to get info on nvme drives
      - SYS_ADMIN
    ports:
      - "${WEB_PORT}:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - config:/opt/scrutiny/config
      - influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/nvme0"

volumes:
  config:
  influxdb:
