---
volumes:
  jellyfin:
  jellyfin-cache:
  jellyseerr:

networks:
  proxy:
    external: true

services:
  # double check if this needs to be in the servarr network
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - jellyfin:/config
      - jellyfin-cache:/cache
      - /mnt/data/media:/media
    networks:
      - proxy     
    restart: 'unless-stopped'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:  
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - jellyseerr:/app/config
    networks:
      - proxy
    restart: 'unless-stopped'

      #jellystat-db:
      #image: postgres
      #environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD_FILE: mypassword
      #
      #jellystat:
      #image: jellystat
      #environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: mypassword
      #POSTGRES_IP: jellystat-db
      #POSTGRES_PORT: 5432
      #JWT_SECRET: 'my-secret-jwt-key'
      #TZ: Africa/Johannesburg
      #ports:
      #- "3000:3000"
      #depends_on:
      #- jellystat-db
      #
