---
# TODO create users
networks:
  servarr:
    external: true

volumes:
  lidarr:
  sonarr:
  radarr:
  readarr:	
  prowlarr:

services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - readarr:/config
      - /mnt/data:/data
    ports:
      - 8787:8787
    networks:
      - servarr
    restart: 'unless-stopped'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - sonarr:/config
      - /mnt/data:/data
    networks:
      - servarr
    restart: 'unless-stopped'

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - radarr:/config
      - /mnt/data:/data
    ports:
      - 7878:7878
    networks:
      - servarr
    restart: 'unless-stopped'

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - lidarr:/config
      - /mnt/data:/data
    ports:
      - 8686:8686    
    networks:
      - servarr     
    restart: 'unless-stopped'

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - prowlarr:/config
      - /mnt/data:/data
    ports:
      - 9696:9696
    networks:
      - servarr     
    restart: 'unless-stopped'
