---
networks:
  snapdrop:
    external: true

volumes:
  config:

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
    networks:
      - snapdrop
    ports:
      - 8652:80
    restart: 'unless-stopped'
