apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/servarr: "true"
        io.kompose.service: jellyseerr
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
          image: fallenbagel/jellyseerr:latest
          name: jellyseerr
          ports:
            - containerPort: 5055
              hostPort: 5055
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr
      restartPolicy: Always
      volumes:
        - name: jellyseerr
          persistentVolumeClaim:
            claimName: jellyseerr
status: {}
