apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/servarr: "true"
        io.kompose.service: jellyfin
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: UMASK
              value: "002"
          image: lscr.io/linuxserver/jellyfin:latest
          name: jellyfin
          ports:
            - containerPort: 8096
              hostPort: 8096
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: jellyfin
            - mountPath: /cache
              name: jellyfin-cache
      restartPolicy: Always
      volumes:
        - name: jellyfin
          hostPath:
            path: /var/local/kubernetes/jellyfin
            type: Directory        
        - name: jellyfin-cache
          hostPath:
            path: /var/local/kubernetes/jellyfin-cache
            type: Directory
status: {}
