---
services:
  collabora:
    image: collabora/code
    restart: 'unless-stopped'
    ports:
      - 9980:9980
    environment:
      - extra_params=--o:ssl.enable=false
    networks:
      - proxy

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: 'unless-stopped'
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 8080:8080
    networks:
      - proxy
    environment: 
      - APACHE_PORT=11000 
      - APACHE_IP_BINDING=0.0.0.0 
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 
      - SKIP_DOMAIN_VALIDATION=true
      - COLLABORA_SECCOMP_DISABLED=true 

volumes: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer 

networks:
  proxy:
    external: true

