---
volumes:
  data:
  letsencrypt:

# TODO automate creation of networks
networks:
  proxy:
    external: true
  # nextcloud-aio creates its own network for its containers, so i need to ad it here
  nextcloud-aio:
    external: true

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    environment:
      # nextcloud AIO wants me to run the reverse proxy as root, TODO see if this is actually necessary (edit /etc/sysctl.conf)
      PUID: 0
      PGID: 0
    networks:
      - proxy
      - nextcloud-aio
    restart: 'unless-stopped'
    # TODO look into if i should be using network mode host?
    #extra_hosts: ["nextcloud-aio-mastercontainer:host-gateway"]
