---
volumes:
  data:
  letsencrypt:

networks:
  gitea:
    external: true
  servarr:
    external: true
  syncthing:
    external: true
  invidious:
    external: true
  snapdrop:
    external: true
  immich:
    external: true
  nextcloud-aio:
    external: true
  homarr:
    external: true

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    environment:
      # nextcloud AIO wants me to run the reverse proxy as root, TODO see if this is actually necessary (edit /etc/sysctl.conf)
      PUID: 0
      PGID: 0
    networks:
      - gitea
      - servarr
      - syncthing
      - invidious
      - snapdrop
      - immich
      - nextcloud-aio
      - homarr
    restart: 'unless-stopped'
    # TODO look into if i should be using network mode host?
    #extra_hosts: ["nextcloud-aio-mastercontainer:host-gateway"]
    network_mode: 'host'
