version: '3.7'

networks:
  radicale:
    external: true

services:
  radicale:
    image: tomsquest/docker-radicale
    ports:
      - 5232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    networks:
      - radicale
    volumes:
      # relative paths don't work with swarm
      - /srv/docker/stacks/radicale/data:/data
      - /srv/docker/stacks/radicale/config:/config:ro
    deploy:
       <<: *deploy
