version: "3"

networks:
  gitea:
    external: false

volumes:
  data:
  config:
  postgres:
  act_runner:

services:
  server:
    image: gitea/gitea:1.20.2-rootless
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA__server_ROOT_URL=${ROOT_URL}
      - GITEA__actions__ENABLED=true
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
    restart: always
    networks:
      - gitea
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3010:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      # ENV variables
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=gitea
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gitea
  runner:
    image: gitea/act_runner
    restart: always
    depends_on:
      - server
    volumes:
      - act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=${INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_TOKEN}
    networks:
      - gitea

