version: "3.8"

# TODO create 'serverarr' user

secrets:
  proton_openvpn_user:
    external: true
  proton_openvpn_password:
    external: true

networks:
  servarr:
    external: true

volumes:
  lidarr:
  sonarr:
  radarr:
  readarr:	
  prowlarr:
  qbittorrent:
  deluge:
  gluetun:

services:
  arch-qbittorrent:
    image: binhex/arch-qbittorrentvpn
    volumes:


  gluetun-launcher:
    image: ixdotai/swarm-launcher:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    secrets:
      - proton_openvpn_user
      - proton_openvpn_password
    environment:
      LAUNCH_IMAGE: 'qmcgaw/gluetun'
      LAUNCH_PROJECT_NAME: 'servarr'
      # checks for latest image and pulls
      LAUNCH_PULL: 'true'
      LAUNCH_EXT_NETWORKS: 'servarr_vpn'
      LAUNCH_CAP_ADD: 'NET_ADMIN'
      LAUNCH_PRIVELEGED: 'true'
      LAUNCH_ENVIRONMENTS: 'VPN_SERVICE_PROVIDER=protonvpn VPN_TYPE=openvpn OPENVPN_USER_SECRETFILE=/run/secrets/proton_openvpn_user OPENVPN_PASSWORD_SECRETFILE=/run/secrets/proton_openvpn_password VPN_PORT_FORWARDING=on'
      LAUNCH_VOLUMES: '/run/secrets/proton_openvpn_user:/run/secrets/proton_openvpn_user /run/secrets/proton_openvpn_password:/run/secrets/proton_opnevpn_password'
      LAUNCH_PORTS: '
        7070:7070
        6881:6881
        6881:6881/udp
        8112:8112
        6882:6882
        6882:6882/udp
        8989:8989'
    networks:
      - servarr
      - vpn
    deploy:
      <<: *deploy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=7070
    volumes:
      - qbittorrent:/config
      - /mnt/data/torrents:/data/torrents
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    networks:
      - servarr    
    deploy:
      <<: *deploy

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - deluge:/config
      - /mnt/data/torrents:/data/torrents
    network_mode: "service:gluetun"
    depends_on:
      - gluetun_launcher
    networks:
      - servarr    
      - vpn
    deploy:
      <<: *deploy

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - readarr:/config
      - /mnt/data:/data
    ports:
      - 8787:8787
    networks:
      - servarr
    deploy:
      <<: *deploy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - sonarr:/config
      - /mnt/data:/data
    networks:
      - servarr
    network_mode: "service:gluetun"
    deploy:
      <<: *deploy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - radarr:/config
      - /mnt/data:/data
    ports:
      - 7878:7878
    networks:
      - servarr
    deploy:
      <<: *deploy

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - lidarr:/config
      - /mnt/data:/data
    ports:
      - 8686:8686    
    networks:
      - servarr     
    deploy:
       <<: *deploy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - prowlarr:/config
      - /mnt/data:/data
    ports:
      - 9696:9696
    networks:
      - servarr     
    deploy:
       <<: *deploy
