---
networks:
  proxy:
    external: true

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    volumes:
      # this feels incredibely unsafe, even if its read only
      - /:/mnt/host:ro
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_PAGE_TITLE=Kamino
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_USE_IMPERIAL=true
    networks:
      - proxy 
