---
volumes:
  config:
  logs:
  data:

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: 'unless-stopped'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.222'
        #gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
    ports:
      - '180:80'
      - '1443:443'
      - '122:22'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'
