version: '3'

services:

  frontend:
    image: "grocy/frontend:v3.3.2"
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '4872:8080'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v3.3.2"
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped

volumes:
  app-db:
