---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0 # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.tipoca.city
    restart: unless-stopped
    networks:
      - proxy

volumes:
  data:

networks:
  proxy:
    external: true
