version: "3.8"

volumes:
  data:
  config:
  postgres:
  act_runner:

secrets:
  gitea_db_passwd:
    external: true
  gitea_runner_token:
    external: true

networks:
  gitea: 
    external: true

services:
  server:
    image: gitea/gitea:latest-rootless
    secrets:
      - gitea_db_passwd
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_db_passwd
      - GITEA__server_ROOT_URL=https://gitea.tipoca.city
      - GITEA__actions__ENABLED=true
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3010:3000"
      - "2222:2222"
    depends_on:
      - db
    networks:
      - gitea
    deploy:
      <<: *deploy

  db:
    image: postgres:14
    secrets:
      - gitea_db_passwd
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=gitea
    volumes:
      - postgres:/var/lib/postgresql/data    
    networks:
      - gitea
    deploy:
      <<: *deploy

  runner:
    image: gitea/act_runner
    depends_on:
      - server
    volumes:
      - act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml
    secrets:
      - gitea_runner_token
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=server:3010
      - GITEA_RUNNER_REGISTRATION_TOKEN__FILE=/run/secrets/gitea_runner_token    
    networks:
      - gitea
    deploy:
      <<: *deploy

