version: "3.8"

# fix theses when im less pissed off
volumes:
  torrent_gluetun:
    external: true
  torrent_qbittorrent:
    external: true
  torrent_deluge:
    external: true

secrets:
  proton_openvpn_username:
    file: /tmp/proton_openvpn_username
  proton_openvpn_password:
    file: /tmp/proton_openvpn_password

networks:
  servarr: 
    external: true

# TODO add health checks
services:
  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 7070:7070 # qbit
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
      - 8112:8112 # deluge
      - 6882:6882 # deluge
      - 6882:6882/udp #deluge
    volumes:
      - torrent_gluetun:/gluetun
    secrets:
      - proton_openvpn_username
      - proton_openvpn_password
    environment:
      # TODO try use a wiregaurd conf instead of openvpn usernames/passwords
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER_SECRETFILE=/run/secrets/proton_openvpn_username
      - OPENVPN_PASSWORD_SECRETFILE=/run/secrets/proton_openvpn_password
      - SERVER_COUNTRIES="United States"
      - VPN_PORT_FORWARDING=on
    networks:
      - servarr

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=7070
    volumes:
      - torrent_qbittorrent:/config
      - /mnt/data/torrents:/data/torrents
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - torrent_deluge:/config
      - /mnt/data/torrents:/data/torrents
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
