version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: kamino
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${SYNC_DIR}:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    network_mode: host
    restart: unless-stopped
