---
networks:
  proxy:
    external: true

services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    environment:
      # TODO password protection maybe?
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
    pid: host
    networks:
      - proxy
    ports: 
      - 61208:61208
