---
# https://github.com/itzg/docker-minecraft-server

# https://minecraft.fandom.com/wiki/Formatting_codes

# TODO add a creative  server

networks:
  proxy:
    internal: true

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    stdin_open: true
    volumes:
      - /srv/minecraft/data:/data
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
        #TYPE: "PAPER"
      MOTD: "Minecraft Survival Server on Kamino"
      DIFFICULTY: "NORMAL"
      # WHITELIST: 
      # OPS: 
      # ICON: "./icon.png"
      MAX_PLAYERS: 999
      ENABLE_COMMAND_BLOCK: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      TZ: US/Eastern
      LOG_TIMESTAMP: "TRUE"
      restart: 'unless-stopped'
