---
volumes:
  data:
  config:
  postgres:
  act_runner:

secrets:
  gitea_db_passwd:
    file: ./secrets/gitea_db_passwd
  runner_registration_token:
    file: ./secrets/runner_registration_token

networks:
  proxy:
    external: true

services:
  server:
    image: gitea/gitea:latest-rootless
    secrets:
      - gitea_db_passwd
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_db_passwd
      - GITEA__server_ROOT_URL=${ROOT_URL}
      - GITEA__actions__ENABLED=true
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=true
      - GITEA__log__ENABLE_SSH_LOG=true
      - GITEA__webhook__ALLOWED_HOST_LIST=external,loopback
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:2222"
    depends_on:
      - db
    restart: 'unless-stopped'    
    networks:
      - proxy


  db:
    image: postgres:14
    secrets:
      - gitea_db_passwd
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=gitea
    volumes:
      - postgres:/var/lib/postgresql/data    
    networks:
      - proxy
    restart: 'unless-stopped'

  runner:
    image: gitea/act_runner
    depends_on:
      - server
    volumes:
      - act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml
    secrets:
      - runner_registration_token
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: https://gitea.tipoca.city/
      GITEA_RUNNER_REGISTRATION_TOKEN_FILE: /run/secrets/runner_registration_token
      GITEA_RUNNER_NAME: gitea-runner-1 
      GITEA_RUNNER_LABELS: ubuntu-latest:docker://node:20-bookworm,ubuntu-22.04:docker://node:20-bookworm,ubuntu-20.04:docker://node:bullseye,ubuntu-18.04:docker://node:buster,cth-ubuntu-latest:docker://catthehacker/ubuntu:act-latest
    networks:
      - proxy
    restart: 'unless-stopped'
